flowchart TD
    classDef start fill:#dfd
    
    subgraph Character Controller
        Idling:::start
        
        WalkingOnFour:::start
        WalkingOnTwo
        Running:::start
        Interacting:::start
        CarryingLightObjects
        CarryingHeavyObjects
        
        Rolling
        LowClimbing
        HighClimbing
        Digging
        MovingLightObjects
        MovingHeavyObjects
        Washing
    end

	WalkingOnFour-->Running
	WalkingOnFour-->WalkingOnTwo
	
	Idling-->WalkingOnFour
	Idling-->Interacting
	Running-->Rolling
	Interacting-->CarryingLightObjects
	CarryingLightObjects-->CarryingHeavyObjects
    WalkingOnTwo-->CarryingHeavyObjects
    WalkingOnTwo-->MovingLightObjects
    WalkingOnTwo-->MovingHeavyObjects
	Interacting-->MovingLightObjects
	MovingLightObjects-->MovingHeavyObjects
	Interacting-->Digging
    Digging-->Washing
	CarryingLightObjects-->Washing
	Interacting-->LowClimbing
	LowClimbing-->HighClimbing