flowchart TD
    classDef start fill:#dfd
    
    subgraph Character Controller
        Idling:::start
        
        WalkingOnFour:::start
        WalkingOnTwo
        Running:::start
        Interacting:::start
        CarryingSmallObjects
        CarryingBigObjects
        
        Rolling
        LowClimbing
        HighClimbing
        Digging
        MovingLightObjects
        MovingHeavyObjects
        Washing
    end

	WalkingOnFour-->Running
	WalkingOnFour-->WalkingOnTwo
	
	Idling-->WalkingOnFour
	Idling-->Interacting
	Running-->Rolling
	Interacting-->CarryingSmallObjects
	CarryingSmallObjects-->CarryingBigObjects
    WalkingOnTwo-->CarryingBigObjects
    WalkingOnTwo-->MovingLightObjects
    WalkingOnTwo-->MovingHeavyObjects
	Interacting-->MovingLightObjects
	MovingLightObjects-->MovingHeavyObjects
	Interacting-->Digging
    Digging-->Washing
	CarryingSmallObjects-->Washing
	Interacting-->LowClimbing
	LowClimbing-->HighClimbing
    
    subgraph World State
        Home:::start
		
		MiaIsAway:::start
		MiaIsInGarden
		MiaIsHome
		
		PenguinsAtConvention:::start
		PenguinsSearchingForBriefcase
		
		HomeDestroyed
	end
	
	MiaIsAway-->MiaIsInGarden
	MiaIsInGarden-->MiaIsHome
	MiaIsHome-->HomeDestroyed
	
	Home-->HomeDestroyed
	
	PenguinsAtConvention-->PenguinsSearchingForBriefcase
	PenguinsSearchingForBriefcase-->HomeDestroyed