name: DocFX

on:
  push:
    branches:
      - 'main'

jobs:
  docfx:
    runs-on: ubuntu-latest
    name: DocFX
    steps:
    - uses: actions/checkout@v3
    
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: Documentation/docfx.json
        
    - uses: peaceiris/actions-gh-pages@v3
      name: Deploy Documentation
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Documentation/html
